name: Print Message

on: [push]

jobs:
  runs_my_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      run: actions/setup-python@v4
    with:
        python-version: 3.11

    - name: Install dependencies
      run: 
      |
        python -m pip instal --upgrade pip
        python install -r requirements.txt

    - name: Run Python file
      run: 
      |
        python app.py

    
