name: Model Training Iris

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run Python file (Model)
      run: |
        python model.py

    - name: Save Model file
      uses: actions/upload-artifact@v4
      with :
        name : model-file
        path: |
          model.joblib 
          output.csv

        

    
